MC/urls.py
from django.conf.urls import url
from . import views
from . import views as core_views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^about/$', views.about, name='about'),
    url(r'^faq/$', views.faq, name='faq'),
    url(r'^test/$', views.test, name='test'),
    url(r'^resources/$', views.resources, name='resources'),
    url(r'^signup/$', core_views.signup, name='signup'),
    url(r'^question/(?P<pk>\d+)/$', views.question_detail, name='question_detail'),
    url(r'^mycheckup$', views.mycheckup, name='mycheckup'),
    url(r'^statement_input/(?P<statement>\d)/(?P<edit>\d+)/$', views.statement_input, name='statement_input'),
    url(r'^statement_help/(?P<state>\d)/(?P<edits>\d+)/$',views.statement_help,name='statement_help'),
    url(r'^score$', views.score, name='score'),
    url(r'^scorelist$', views.scorelist, name='scorelist'),
    url(r'^scoresheet/(?P<pk>\d+)/$', views.scoresheet, name='scoresheet'),
    url(r'^otherscore/(?P<number>\d+)/$', views.otherscore, name='otherscore'),
    url(r'^statement_wellness/(?P<statement>\d)/(?P<pk>\d+)/$', views.statement_wellness, name='statement_wellness'),
]

check/urls.py
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

# Use include() to add URLS from the catalog application
from django.conf.urls import include

urlpatterns += [
    url(r'^MC/', include('MC.urls')),
]

#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    url(r'^accounts/', include('django.contrib.auth.urls')),
]

#Add URL maps to redirect the base URL to our application
#redirects site from basic IP to /check
from django.views.generic import RedirectView
from django.conf.urls import url
#from django.core.urlresolvers import reverse_lazy

urlpatterns += [url(r'^$', RedirectView.as_view(url='/MC/', permanent=True)),]
urlpatterns += [url(r'accounts/profile$', RedirectView.as_view(url='/', permanent=True)),]
urlpatterns += [url(r'accounts/profile', RedirectView.as_view(url='/', permanent=True)),]

#redirect to home
#url(r'^accounts/profile$', RedirectView.as_view(permanent=False))
#url(r'^$', RedirectView.as_view(url=reverse_lazy('app_dashboard')), name='index'),
#urlpatterns = [(r'^accounts/profile$', views.url_redirect, name="url-redirect"),]

#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    url(r'^accounts/', include('django.contrib.auth.urls')),]

#Below are patterns that this generates
#accounts/ login/ [name='login']
#accounts/ logout/ [name='logout']
#accounts/ password_change/ [name='password_change']
#accounts/ password_change/done/ [name='password_change_done']
#accounts/ password_reset/ [name='password_reset']
#accounts/ password_reset/done/ [name='password_reset_done']
#accounts/ reset/<uidb64>/<token>/ [name='password_reset_confirm']
#accounts/ reset/done/ [name='password_reset_complete']

# Use static() to add url mapping to serve static files during development (only)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


#urlpatterns = [url(r'^accounts/profile/$', RedirectView.as_view(url='/MC/', permanent=True)),]

MC/models.py
from django.db import models
from django.utils import timezone
#from django import forms

# Create your models here.

NUMBER = (
    (1,1),
    (2,2),
    (3,3),
    (4,4),
    (5,5),
)

class QuestionManager(models.Manager):
    def current_for_user(self,user):
        question1 = Question.objects.filter(author=user,statementNumber=1).order_by('-id').first()
        question2 = Question.objects.filter(author=user,statementNumber=2).order_by('-id').first()
        question3 = Question.objects.filter(author=user,statementNumber=3).order_by('-id').first()
        question4 = Question.objects.filter(author=user,statementNumber=4).order_by('-id').first()
        question5 = Question.objects.filter(author=user,statementNumber=5).order_by('-id').first()

        question_list = {"1":question1,
                        "2":question2,
                        "3":question3,
                        "4":question4,
                        "5":question5}
        return question_list

class Question(models.Model):
    statementNumber=models.IntegerField(choices=NUMBER, default='1',verbose_name="The number of the statement")
    text = models.CharField(max_length=500,help_text="Enter Your Statement", verbose_name="")
    #text = models.TextField(help_text="Enter your Statement")
    author = models.ForeignKey('auth.User',on_delete=models.PROTECT)
    date_created = models.DateTimeField(blank=False, null=False)
    objects=QuestionManager()


    def save(self, *args, **kwargs):
        self.date_created = timezone.now()
        super(Question, self).save(*args, **kwargs)

    def __str__(self):
        return self.text

class ScoreManager (models.Manager):
    def get_userset(self,user):

        UserScores = Score.objects.filter(author=user)
        #UserScores = Score.objects.filter(author=user).count()

        return UserScores


class DataManager (models.Manager):
    def list(self,user):
        result_list=Score.objects.filter(author=user).values().order_by("-id")
        return result_list

class Score(models.Model):

    yesno = ((1,"Yes"),(0,"No"),)
    bigfive = ((0,"Really Bad"),
               (1,"Bad"),
               (2,"Ok"),
               (3,"Good"),
               (4,"Really Good"),)

    statementNumber=models.IntegerField(default='1',verbose_name="The number of the statement")
    author = models.ForeignKey('auth.User',on_delete=models.PROTECT)
    date_created = models.DateTimeField(blank=False, null=False)
    onepk=models.IntegerField(default='1')
    twopk=models.IntegerField(default='1')
    threepk=models.IntegerField(default='1')
    fourpk=models.IntegerField(default='1')
    fivepk=models.IntegerField(default='1')
    oneScore = models.IntegerField(choices=yesno,default='none',verbose_name="statement 1")
    twoScore = models.IntegerField(choices=yesno, default='none',verbose_name="statement 2")
    threeScore = models.IntegerField(choices=yesno, default='none',verbose_name="statement 3")
    fourScore= models.IntegerField(choices=yesno, default='none',verbose_name="statement 4")
    fiveScore= models.IntegerField(choices=yesno, default='none',verbose_name="statement 5")
    bigScore= models.IntegerField(choices=bigfive, default='3',verbose_name="How were you feeling?")

    objects = models.Manager()
    user_objects = ScoreManager()
    data_objects = DataManager()

    def save(self, *args, **kwargs):
        self.date_created = timezone.now()
        super(Score, self).save(*args, **kwargs)

    def __str__(self):
        return str(self.id)

MC/views.py
from django.shortcuts import render
from .models import Question,Score
from . import views
from django import forms

def home(request):
    sampleUser = "1"
    sample = Question.objects.current_for_user(sampleUser)
    mod = 0
    if request.user.is_authenticated:
        user = request.user
        questions = Question.objects.current_for_user(user)
        if questions['1']== None or questions['2']== None or questions['3']== None or questions['4']== None or questions['5'] == None:
            mod = 1
    else:
        user = request.user
        questions = Question.objects.current_for_user(sampleUser)
    return render(request,'MC/content.html',{'sample':sorted(sample.items()),'questions':sorted(questions.items()),'mod':mod})

def about(request):
    return render(request,'MC/about.html')

def faq(request):
    return render(request,'MC/FAQ.html')

def resources(request):
    return render(request,'MC/resources.html')

def test(request):
    sampleUser = "1"
    sample = Question.objects.current_for_user(sampleUser)
    mod = 0
    if request.user.is_authenticated:
        user = request.user
        questions = Question.objects.current_for_user(user)
        if questions['1']== None or questions['2']== None or questions['3']== None or questions['4']== None or questions['5'] == None:
            mod = 1
    else:
        user = request.user
        questions = Question.objects.current_for_user(sampleUser)
    return render(request,'MC/test.html',{'sample':sorted(sample.items()),'questions':sorted(questions.items()),'mod':mod})


#allows user to SIGN UP
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login, authenticate
from django.shortcuts import render, redirect
from .forms import SignUpForm

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('home')
    else:
        form = SignUpForm()
    return render(request, 'registration/signup.html', {'form': form})

from django.shortcuts import redirect
from .forms import QuestionForm,StatementForm,ScoreForm
from django.utils import timezone
from django.shortcuts import render, get_object_or_404

def statement_input(request,statement,edit):
    user = request.user
    sampleUser = "1"
    questions = Question.objects.current_for_user(user)
    sample= Question.objects.current_for_user(sampleUser)
    if request.method == "POST":
        form = StatementForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user
            question.statementNumber=statement
            question.save()
            return redirect('question_detail', pk=question.pk)
    else:
        form = StatementForm()

    return render(request,'MC/statement_input.html',{'form': form,'questions': sorted(questions.items()),'statement':statement,'sample':sorted(sample.items()),'edit':edit})

def statement_help(request,state,edits):
    sampleUser = "1"
    sample = Question.objects.current_for_user(sampleUser)
    return render(request,'MC/statementhelp.html',{'sample':sorted(sample.items()),'state':state,'edits':edits})

def question_detail(request, pk):
    question = get_object_or_404(Question, pk=pk)
    return render(request, 'MC/question_detail.html',{'question': question})

from django.contrib.auth.models import User

def mycheckup(request):
    user = request.user
    questions = Question.objects.current_for_user(user)
    mod = 0
    if questions['1']== None or questions['2']== None or questions['3']== None or questions['4']== None or questions['5'] == None:
        mod = 1
    return render(request, 'MC/mycheckup.html',{'questions': sorted(questions.items()),'mod':mod})

def url_redirect(request):
    return HttpResponsePermanentRedirect("/MC")

def score(request):
    user = request.user
    questions = Question.objects.current_for_user(user)
    yesno = ((1,"Yes"),(0,"No"),)
    bigfive = ((0,"Really Bad"),
               (1,"Poorly"),
               (2,"Ok"),
               (3,"Pretty Good"),
               (4,"Really Good"),)

    if request.method == "POST":
        form = ScoreForm(request.POST)
        if form.is_valid():
            score = form.save(commit=False)
            questions = Question.objects.current_for_user(user)
            score.onepk = questions["1"].id
            score.twopk = questions["2"].id
            score.threepk= questions["3"].id
            score.fourpk = questions["4"].id
            score.fivepk = questions["5"].id
            score.author = request.user
            score.save()
            return redirect('scoresheet',pk=score.pk)
    else:
        form = ScoreForm(questions)

    return render(request,'MC/score.html',{'form': form,'questions':questions,'yesno':yesno,'bigfive':bigfive})

def scoresheet (request,pk):
    user = request.user
    scores = Score.user_objects.get_userset(user).count()
    data = Score.data_objects.list(user)
    questions = Question.objects.current_for_user(user)
    bigscorenow = 0
    scorenow = 0
    score2 = 0
    score3 = 0
    date1 ="Not yet completed"
    date2= "Not yet completed"
    date3= "Not yet completed"
    z1 = 0
    z2 = 0
    z3 = 0
    z4 = 0
    z5 = 0

    import datetime

    if len(data)>2:
        thirdScore = data[2]
        score3 = thirdScore["oneScore"]+thirdScore["twoScore"]+thirdScore["threeScore"]+thirdScore["fourScore"]+thirdScore["fiveScore"]
        score3date = thirdScore["date_created"]
        date3=score3date.strftime('%A %d/%m/%Y')
    if len(data)>1:
        secondScore = data[1]
        score2 = secondScore["oneScore"]+secondScore["twoScore"]+secondScore["threeScore"]+secondScore["fourScore"]+secondScore["fiveScore"]
        score2date = secondScore["date_created"]
        date2=score2date.strftime('%A %d/%m/%Y')
    if len(data)>0:
        lastScore = data.first()
        scorenow = lastScore["oneScore"]+lastScore["twoScore"]+lastScore["threeScore"]+lastScore["fourScore"]+lastScore["fiveScore"]
        bigscorenow = lastScore["bigScore"]
        score1date= lastScore["date_created"]
        date1=score1date.strftime('%A %d/%m/%Y')
        pk1=lastScore["onepk"]
        pk2=lastScore["twopk"]
        pk3=lastScore["threepk"]
        pk4=lastScore["fourpk"]
        pk5=lastScore["fivepk"]
        x1 = Score.objects.filter(author=user,onepk=pk1).count()
        y1=Score.objects.filter(author=user,onepk=pk1,oneScore=1).count()
        z1=round(y1/x1*100,1)
        x2 = Score.objects.filter(author=user,twopk=pk2).count()
        y2=Score.objects.filter(author=user,twopk=pk2,twoScore=1).count()
        z2=round(y2/x2*100,1)
        x3 = Score.objects.filter(author=user,threepk=pk3).count()
        y3=Score.objects.filter(author=user,threepk=pk3,threeScore=1).count()
        z3=round(y3/x3*100,1)
        x4 = Score.objects.filter(author=user,fourpk=pk4).count()
        y4=Score.objects.filter(author=user,fourpk=pk4,fourScore=1).count()
        z4=round(y4/x4*100,1)
        x5 = Score.objects.filter(author=user,fivepk=pk5).count()
        y5=Score.objects.filter(author=user,fivepk=pk5,fiveScore=1).count()
        z5=round(y5/x5*100,1)


    return render(request, 'MC/Scoresheet.html',{'scores':scores,'data':data,'scorenow':scorenow,'date1':date1, 'bigscorenow':bigscorenow, 'score2':score2,'score3':score3,'questions': questions, 'z1':z1, 'z2':z2,'z3':z3,'z4':z4,'z5':z5, 'date2':date2,'date3':date3,'pk':pk})


def otherscore (request,number):
    user = request.user
    data = Score.data_objects.list(user)
    thisscore = data[int(number)]
    otherdate= thisscore["date_created"]
    firstpk = thisscore["onepk"]

    question1 = Question.objects.filter(author=user,pk=thisscore["onepk"]).last()
    question2 = Question.objects.filter(author=user,pk=thisscore["twopk"]).last()
    question3 = Question.objects.filter(author=user,pk=thisscore["threepk"]).last()
    question4 = Question.objects.filter(author=user,pk=thisscore["fourpk"]).last()
    question5 = Question.objects.filter(author=user,pk=thisscore["fivepk"]).last()

    one = thisscore["oneScore"]
    two = thisscore["twoScore"]
    three = thisscore["threeScore"]
    four = thisscore["fourScore"]
    five = thisscore["fiveScore"]

    scorelist=(one,two,three,four,five)
    score = thisscore["oneScore"]+thisscore["twoScore"]+thisscore["threeScore"]+thisscore["fourScore"]+thisscore["fiveScore"]
    bigone= thisscore["bigScore"]

    if bigone==4:
        wellness="Really Good"
    elif bigone==3:
        wellness="Good"
    elif bigone==2:
        wellness="OK"
    elif bigone==1:
        wellness="Bad"
    else:
        wellness="Really Bad"

    question_list = {"1":question1,
                    "2":question2,
                    "3":question3,
                    "4":question4,
                    "5":question5}

    return render(request, 'MC/otherscore.html', {'otherdate':otherdate, 'thisscore':thisscore, 'question_list':question_list, 'score':score,'scorelist':scorelist,'wellness':wellness})


def scorelist (request):
    user = request.user
    scores = Score.user_objects.get_userset(user).count()
    data = Score.data_objects.list(user)
    thislist=[]
    x=0;

    for one in data:
        date=one["date_created"].strftime('%A %d/%m/%Y')
        thislist.append(date)
        x=x+1

    return render (request, 'MC/scorelist.html', {'scores':scores,'data':data,'thislist':thislist})

from django.db.models import Avg
def statement_wellness (request,statement,pk):
    user = request.user
    question = Question.objects.filter(author=user,pk=pk).last()

    if int(statement) == 1:
        score_no=Score.objects.filter(onepk=pk,oneScore=0).aggregate(Avg('bigScore'))

MC/templates/MC/FAQ.html
{% extends 'generic.html' %}
{% load static %}

{% block content %}

<div class = "intro2">
  <p> Frequently Asked Questions</p>
</div>

<div class = "textbox2">
<p><b> Why participate?</b></p>
<p>My Checkup is a commitment to getting to know yourself and to finding the person you enjoy being. This tool is currently being developed, and can promise no studied outcomes. By participating, we hope you will give us feedback make this tool as useful as possible and to study its uses. We believe My Checkup can act to improve your understanding of yourself and also to warn you when your mindset is changing.</p>
</div>

{% endblock %}

MC/templates/MC/Scoresheet.html
{% extends 'generic.html' %}
{% block content %}

<!--detects post checkup OR stats check based on pk delivered to url-->
{%if pk == "0"%}
<h2>{{ user.get_username|title }}'s Stats </h2>
{% else %}
<h2> Checkup Complete! </h2>
<h3>STATS</h3>
{% endif %}


{%if pk != "0"%}

<div class = "textbox">
<p> You are doing <strong>{{scorenow}}/5</strong> of your statements regularly</p>
</div>

<div class = "button2">
<button>What's it mean?</button>
</div>
<script>
$("button").click(function() {
  $( "#clickme" ).toggle();
});
</script>

<div id = "clickme" style="display:none">
<div class = "textbox2">
{%if scorenow > 3%}
  {%if bigscorenow > 2%}
  <p><b>You are definitely living true to Your Checkup.</b></p>
  <p> Considering your Statements regularly can you keep you grounded and well. Good work!</p>
  {%else%}
  <p><b>You are living true to Your Checkup.</b></p>
  <p> But you are still <b>not feeling great</b>. It may be a good time to try one of the following:
  <ul>
    <li>Stay the course. We all feel down sometimes - that's normal as long as it passes.</li>
    <li><a href="{% url 'mycheckup' %}"> Changing Your Checkup Statements</a> - to make different intentions.</li>
    <li>Ask for help from someone who cares.</li>
    <li> <a href ="{% url 'resources' %}">Here are some resources</a> that you might find valuable</li>

  </ul>
  {%endif%}

{%elif scorenow > 1%}
<p><b>You are sometimes doing the things on Your Checkup.</b> </p>
  {%if bigscorenow > 2%}
  <p> However, you are still feeling good. This may mean:</p>
  <ul>
    <li>You feel good. Don't overthink it.</li>
    <li>You feel good. But you could feel even better if you kept up with the things on Your Checkup.</li>
    <li><a href="{% url 'mycheckup' %}"> Edit Your Checkup</a>: Your Checkup items could be reconsidered - what are you doing/thinking that keeps you doing well?</li>
  </ul>
  {%else%}
  <p> This may be a good moment to ask yourself if things are going OK. If you are struggling, that's OK - we all do sometimes. It may be time to make some changes or else reconsider your My Checkup Questions.</p>
  <p> <a href ="{% url 'resources' %}">Here are some resources</a> that you might find valuable</p>
  {%endif%}
{%else %}
  <p><b>You are rarely doing the things on Your CheckUp. </b></p>
  {%if bigscorenow > 2%}
  <p> However, you are still feeling good. This may mean:</p>
  <ul>
    <li>You feel good. Don't overthink it.</li>
    <li>You feel good. But you could feel even better if you kept up with the things on Your Checkup.</li>
    <li><a href="{% url 'mycheckup' %}"> Edit Your Checkup</a>: Your Checkup items could be reconsidered - what are you doing/thinking that keeps you doing well? </li>
  </ul>
  {%else%}
  <p> This might be a moment to reconsider whether you are coping OK or happy with where you are at. If it's temporary, no worries! If you find your scores low on a regular basis, think about asking someone for help or changing things up.
  <br>
  <p> We believe in you. </p>
  <br>
  <p> <a href ="{% url 'resources' %}">Here are some resources</a> that you might find valuable</p>
  {%endif%}
{%endif%}
</div>
</div>
{% endif %}

<div class = "textbox4">
<p>You have performed <b>{{scores}}</b> Checkups with yourself</p>
</div>

{%if pk == "0" %}
  <div class = "textbox4">
  {% if date1 != "Not yet completed" %}
    <p><b> Past Scores </b></p>
    <p>  <b>{{scorenow}}/5</b> on {{date1}}</p>
    {% if date2 != "Not yet completed" %}
    <a href ={% url 'otherscore' number=1 %}><p>  <b>{{score2}}/5</b> on {{date2}} </p></a>
      {% if date3 != "Not yet completed" %}
      <a href ={% url 'otherscore' number=2 %}><p><b>{{score3}}/5</b> on {{date3}}</a></p>
      <p><a href ="{% url 'scorelist' %}">All Scores</a></p>
      {% endif %}
    {% endif %}
  {% endif %}
  </div>
{% else %}
  <div class = "textbox4">
  {% if date2 != "Not yet completed" %}
    <p> Your last scores were:</p>
    <a href ={% url 'otherscore' number=1 %}><p>  <b>{{score2}}/5</b> on {{date2}} </a></p>
    {% if date3 != "Not yet completed" %}
    <a href ={% url 'otherscore' number=2 %}><p><b>{{score3}}/5</b> on {{date3}}</a></p>
    <p><a href ="{% url 'scorelist' %}">All Scores</a></p>
    {% endif %}
  {% endif %}
  </div>
{% endif %}

<br>

{% if date1 != "Not yet completed" %}
<div class = "row">
<div class = "col-sm-8">
<div class ="statement_1">
<p><b><a class = "nounderline" href={% url 'statement_wellness' statement=1 pk=questions.1.pk %}>{{questions.1}}</a></b></p>
<p> You do this {{z1}}% of the time </p>
</div>

<div class ="statement_2">
<p><b><a class = "nounderline" href={% url 'statement_wellness' statement=2 pk=questions.2.pk %}>{{questions.2}}</a></b></p>
<p> You do this {{z2}}% of the time </p>
</div>

<div class ="statement_3">
<p><b><a class = "nounderline" href={% url 'statement_wellness' statement=3 pk=questions.3.pk %}>{{questions.3}}</a></b></p>
<p> You do this {{z3}}% of the time </p>
</div>

<div class ="statement_4">
<p><b><a class = "nounderline" href={% url 'statement_wellness' statement=4 pk=questions.4.pk %}>{{questions.4}}</a></b></p>
<p> You do this {{z4}}% of the time </p>
</div>

<div class ="statement_5">
<p><b><a class = "nounderline" href={% url 'statement_wellness' statement=5 pk=questions.5.pk %}>{{questions.5}}</a></b></p>
<p> You do this {{z5}}% of the time </p>
</div>
</div>
</div>
{% endif %}

<h2><a href="{% url 'home' %}">Back to My CheckUp</a> </h2>


{%endblock%}

MC/templates/MC/delete_question.html
{% extends 'generic.html' %}

{% block content %}
<!--  <p> Author:{{ user.get_username }}</p>

  {% for question in questions %}
        <p> {{forloop.counter}}) {{ question.text }} </p>
  {% endfor %}-->

{% endblock %}

MC/templates/MC/mycheckup.html
{% extends 'generic.html' %}

{% block content %}

<h2> {{ user.get_username|title }}'s CheckUp</h2>
<h4><b> Click a statement to edit</b></h4>
<br>
<div class = "textbox2">
<p>Ask yourself: Are you generally...</p>
</div>

  {% for key, val in questions %}
  {%if val == None%}
    <div class = "statement_{{key}}">
      <p><a class = "mc" href={% url 'statement_input' statement=key edit=0  %}> Create a new statement </a></p>
    </div>
  {%else%}
    <div class = "statement_{{key}}">
      <p>{{ key }}) <a class ="mc" href={% url 'statement_input' statement=key edit=1 %}>{{val}}</a></p>
    </div>
  {%endif%}
  {% endfor %}

  {% if mod == 0 %}
    <br>
    <h3 ><center><a class = "button" href="{% url 'score' %}">Time to Check-In</center></a></h3>
    <br>
  {%endif%}

<div class = "textbox2">
<p><b>What does it mean? </b></p>
<ul>
<li> MyCheckup is a way for you to think about your wellness.</li>
<div class = "textbox3">
<li> If you are able to incorporate your CheckUp statements into your life, great. This should be a sign you're on the right track.</li>
</div>
<li> If you still aren't feeling well, in spite of following your statements - you could give them more time or try changing them to shift your focus.</li>
<div class = "textbox3">
<li> If you aren't able to perform your CheckUp statements - no problem. This is common. You may have other worries, be too busy, or have other interests. If you want a change, consider re-thinking your statements. </li>
</div>
</ul>
</div>






{% endblock %}

MC/templates/MC/question_detail.html
{% extends 'generic.html' %}

{% block content %}


      <div class ="statement_{{question.statementNumber}}">
        <p> Your new Statement: </p>
        <h1>{{ question.text }}</h1>
      </div>

        <h2><a href="{% url 'home' %}"> Go to My CheckUp.</h2>


{% endblock %}

MC/templates/MC/resources.html
{% extends 'generic.html' %}
{% load static %}

{% block content %}

<div class = "textbox2">
<ul>
  <li><a href = "http://www.growingresilient.com">Growing Resilient</a> - a website we curate to build skills and improve wellness.</li>
  <li><a href = "http://www.headspace.com">Headspace</a> - a website and app encourages mindfulness and meditation </li>
</ul>
</div>

{% endblock %}

MC/templates/MC/score.html
{% extends 'generic.html' %}
{% load crispy_forms_tags %}

{% block content %}

<h2>Time for a Checkup</h2>

  <form method="POST" class="post-form">
    {% csrf_token %}

    <div class = "form">
            <p><label for="id_bigScore"><b>How have you been feeling?</label></p>
            <p><select name="bigScore">
                  <option value="4">Really Good</option>
                  <option value="3">Good</option>
                  <option value="2">OK</option>
                  <option value="1">Bad</option>
                  <option value="0">Really Bad</option>
              </select> </p>
              <br>
              <br>
              <h4> Since your last Checkup, were you generally doing the following?</h4>
              <br>


              <p><label for="id_oneScore">{{questions.1}}</label><p>
              <p><fieldset id="id_oneScore">
                      <input type="radio" name="oneScore" option value="1">Yes</option>
                      <input type="radio" name="oneScore" option value="0">No</option>
                    </fieldset></p>
                <p><label for="twoScore">{{questions.2}}</label></p>
                <p><fieldset id="id_twoScore">
                      <input type="radio" name="twoScore" option value="1">Yes</option>
                      <input type="radio" name="twoScore" option value="0">No</option>
                    </fieldset> </p>
                <p><label for="id_threeScore">{{questions.3}}</label></p>
                <p><fieldset id="id_threeScore">
                      <input type="radio" name="threeScore" option value="1">Yes</option>
                      <input type="radio" name="threeScore" option value="0">No</option>
                    </fieldset> </p>
                <p><label for="id_name">{{questions.4}}</label></p>
                <p><fieldset id="id_fourScore">
                      <input type="radio" name="fourScore" option value="1">Yes</option>
                      <input type="radio" name="fourScore" option value="0">No</option>
                    </fieldset> </p>
                <p><label for="id_name">{{questions.5}}</label></p>
                <p><fieldset id="id_fiveScore">
                      <input type="radio" name="fiveScore" option value="1">Yes</option>
                      <input type="radio" name="fiveScore" option value="0">No</option>
                    </fieldset> </p>

    <br>
    <button type="submit" class="save btn btn-default">Check In</button>
    </div>
  </form>


</div>



{% endblock%}